
## BDMPS Population Sizes {#bdmpspopulationsizes}

### Summary {-}
The raw population data that underpin the BDMPS. This file provides the size (# pairs of breeding adults) of each population, whether a UK SPA, aggregate of UK non-SPA colonies, or aggregate of overseas colonies.

### Provenance {-}
This dataset was derived by automatically converting the tables of appendices (Tables 1-69) from the  BDMPS report [@furness_2015] into to a CSV file, importing this into R, and then using an R script to extract the raw data that underpin the BDMPS calculations. This process was designed to separate out the raw data that underpin BDMPS from the derived values within it, and to put it into a format that is easily accessed by R, to enable the BDMPS calculations to be implemented as a tool within the CEF, and to make future updating of the raw input data as straightforward as possible.

### Terms of Use {-}
These data are from published reports and are freely available to use, subject to standard copyright terms.


#### Update information {-}
* No updates available


### Supplemental information {-}
These raw data are used by the BDMPS tool to produce apportioning percentages (usually, although not necessarily, for the non-breeding season)

### Keywords {-}
seabirds; spatial distribution; apportioning; non-breeding season; BDMPS

----

